config/routes.rb
Rails.application.routes.draw do

  get "login" => "sessions#new"
  post "login" => "sessions#create"
  delete "logout" => "sessions#destroy"
  resources :users
  resources :wards do
    patch 'reduce' => 'wards#reduce'
  end
  resources :patients do
    member do
      get :edit2
      get :edit3
      patch :update2
      patch :update3
    end
  end
  resources :patient_admissions
  root "sessions#new"
  resources :insurance
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/insurance_table.rb
class InsuranceTable < ApplicationRecord
  belongs_to :user
end

app/controllers/insurance_controller.rb
class InsuranceController < ApplicationController
before_action :is_authenticated

  def index
    #create an instance to be used, refer to the model,
    #find by user id for all insurances, check that it matches current user's id,
    #before executing the following action
    if current_user # if you're logged in
      @insurance = InsuranceTable.where(user_id: current_user.id)
      @patient = PatientAdmission.find_by user_id: current_user.id, confirm: false
    else
      redirect_to new_insurance_path #prefix_path or prefix_url
    end
  end

  def show
    @insurance = InsuranceTable.find(params[:id])
    if @insurance.user_id == current_user.id
      render :show
    else
      redirect_to insurance_index_path
    end
  end

  def new
    @insurance= InsuranceTable.new
  end

  def create
    @insurance= InsuranceTable.new(insurance_params)
    @insurance["user_id"]= current_user.id #need to referrence to a user id as it is a foreign key
    if @insurance.save
      flash[:success] = "Policy Details saved"
      redirect_to insurance_index_path
    else
      render :new
    end
  end

    def update
      #computer does not remember that edit was ran
      @insurance=InsuranceTable.find_by_id(params[:id])
      if @insurance.update(insurance_params)
        redirect_to insurance_index_path
      else
        redirect_to edit_insurance_path
      end
    end

    def edit
      @insurance=InsuranceTable.find_by_id(params[:id])
    end

    def destroy

      @insurance=InsuranceTable.find(params[:id])
      @insurance.destroy
      redirect_to insurance_index_path
    end

    private

    def insurance_params
      params.require(:insurance).permit(:insurance_company, :id, :insurance_name, :insurance_type, :claimable_amount)
    end
end

app/helpers/insurance_helper.rb
module InsuranceHelper
end

app/views/insurance/edit.html.erb
<div class="container">
 <div class="page-header">
    <h1>Please edit you insurance details</h1>
  </div><br>
   <%= form_for :insurance, url: insurance_path(@insurance), html: {method: "patch"} do |t| %>

     <%= t.label :insurance_company %>
     <%= t.text_area :insurance_company, class:"form-control" %>

     <%= t.label :insurance_name %>
     <%= t.text_area :insurance_name, class:"form-control" %>

     <%= t.label :insurance_type %>
     <%= t.text_area :insurance_type, class:"form-control" %>

     <%= t.label :claimable_amount %>
     <%= t.text_area :claimable_amount, class:"form-control"  %>
      <br>
    <%= t.submit "Save changes", class: "btn btn-primary btn-lg" %>
    <% end %>

</div>

app/views/insurance/index.html.erb
<div class="container">
<% if @insurance.length == 0 %>
<div class="page-header">
  <h1>Record of Insurance Policies</h1>
</div>
<h4>You do not have any insurance policies on record with us. Pls add more for your records.</h4>
<%= button_to "Create new entries", new_insurance_path, class: "btn btn-primary btn-lg", method: :get %>
<% else %>
  <div class="page-header">
    <h1>Record of insurance policies</h1>
  </div>
  <%= button_to "Create new entries", new_insurance_path, class: "btn btn-primary btn-lg" , method: :get %>
  <br>
  <table id="t1">
    <tr>
      <td> Insurance Company </td>
      <td> Insurance Name </td>
      <td> Insurance Type </td>
      <td> Claimable Amount </td>
      <td> Edit </td>
      <td> Delete</td>
    </tr>
    <% @insurance.each do |i| %>
    <tr>
      <th style="width:20%"><%= i.insurance_company %></th>
      <th style="width:30%"><%= i.insurance_name %></th>
      <th style="width:20%"><%= i.insurance_type %></th>
      <th style="width:10%"><%= i.claimable_amount %></th>
      <th style="width:10%"><%= link_to "Edit", edit_insurance_path(i.id), class: 'btn btn-primary' %></th>
      <th style="width:10%"><%= button_to "Delete", insurance_path(i.id), method: :delete, class: 'btn btn-primary' %></th>
    </tr>
    <% end %>
  </table>
  <% end %>
  <br>

  <% if @patient != nil %>
  <%= link_to 'Bill', edit_patient_admission_path(current_user.id), class: "btn btn-primary btn-lg"%>
  <% end %>
  <p> </p>
  <%= link_to 'Personal Details Page', user_path(current_user.id), class:"btn btn-lg btn-primary" %>
</div>

app/views/insurance/new.html.erb
<div class="container">
 <div class="page-header">
   <h1>Please enter new insurance policy details</h1>
 </div><br>
   <%= form_for :insurance, url: insurance_index_path,  html: {method: "post"} do |t| %>

     <%= t.label :insurance_company %>
     <%= t.text_area :insurance_company, class:"form-control" %>

     <%= t.label :insurance_name %>
     <%= t.text_area :insurance_name, class:"form-control" %>

     <%= t.label :insurance_type %>
     <%= t.text_area :insurance_type, class:"form-control" %>

     <%= t.label :claimable_amount %>
     <%= t.text_area :claimable_amount, class:"form-control"  %>
      <br>
     <%= t.submit "Create policy", class: "btn btn-primary btn-lg" %>
    <% end %>

</div>