config/routes.rb
Rails.application.routes.draw do

  get "login" => "sessions#new"
  post "login" => "sessions#create"
  delete "logout" => "sessions#destroy"
  resources :users
  resources :wards do
    patch 'reduce' => 'wards#reduce'
  end
  resources :patients do
    member do
      get :edit2
      get :edit3
      patch :update2
      patch :update3
    end
  end
  resources :patient_admissions
  root "sessions#new"
  resources :insurance
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  has_one :patient
  has_many :insurance_tables, dependent: :destroy

  validates :personal_id,
  presence: true,
  uniqueness: {case_sensitive: false},
  format: /\A[STFG]\d{7}[A-Z]\z/

  validates :email,
  presence: true,
  uniqueness: {case_sensitive: false},
  format: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :password,
  length: { in: 8..72 },
  on: :create

  validates :name,
  presence: true

  validates :contact_no,
  presence: true,
  numericality: true,
  length: { :minimum => 8, :maximum => 8 }

  has_secure_password

  def self.find_and_authenticate_user(params)
    User.find_by_personal_id(params[:personal_id]).try(:authenticate, params[:password])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # before_action :is_authenticated

  # def index
  #   redirect_to new_user_path
  # end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      # Tell the UserMailer to send a welcome email after save
      UserMailer.welcome_email(@user).deliver_now

      flash[:success] = 'Account created & email sent. Please Login.'
      redirect_to login_path

    else
      flash[:error] = @user.errors.full_messages
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to @user
      flash[:success] = 'User profile successfully updated.'
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :personal_id, :name, :contact_no)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class="container">
  <div class="container page-header">
    <h1>Updating...</h1>
  </div>

  <%= form_for :user, url: user_path(current_user.id), method: :patch do |f| %>

    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>

    <%= f.label :email %>
    <%= f.email_field :email, class: 'form-control' %>

    <%= f.label :contact_no %>
    <%= f.telephone_field :contact_no, class: 'form-control' %>

    <%= f.label :password %>
    <%= f.password_field :password, class: 'form-control' %>
    <br>

    <%= f.button "Save changes", class: 'btn btn-lg btn-primary' %>
  <% end %>
</div>

app/views/users/index.html.erb
<div class="container jumbotron">
<h1>Login</h1>
<h3>Welcome to eFinancialCounsellor, pls login to start the admission process.</h3>
</div>

<%= render "partials/flash" %>

<%= form_for :user do |f| %>
  <%= f.text_field :personal_id, placeholder: "Enter your NRIC/FIN" %>
  <%= f.text_field :password, placeholder: "Enter your password" %>

  <%= f.submit "Login" %>
<% end %>

app/views/users/new.html.erb
<div class="container">
  <div class="page-header">
    <h1>Register</h1>
  </div>

  <div>
  <%= form_for @user, url: users_path do |f| %>
  <% if @user.errors.any? %>
     <div id="error_explanation">
       <h2><%= pluralize(@user.errors.count, "error") %>
         prohibited this user from signing up:</h2>
       <ul>
         <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
         <% end %>
       </ul>
     </div>
     <% end %>
  <%= f.text_field :personal_id, placeholder: "Enter your personal_id/FIN", class: 'form-control fontinput' %> <br>
  <%= f.text_field :name, placeholder: "Enter your name", class: 'form-control fontinput' %> <br>
  <%= f.text_field :email, placeholder: "Enter your email", class: 'form-control fontinput' %> <br>
  <%= f.password_field :password, placeholder: "Enter your password", class: 'form-control fontinput' %> <br>
  <%= f.text_field :contact_no, placeholder: "Enter your contact number", class: 'form-control fontinput' %> <br>

  <%= f.submit "Register", class: 'btn btn-primary btn-lg' %>
  <% end %>
</div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="container page-header">

    <h1> User Profile | <%= link_to "Insurance Details", insurance_index_path %> | <%= link_to "Next-of-kin Details", edit3_patient_path %></h1>

  </div>


<table>
  <thead>
    <%= render 'partials/flash' %>
    <tr>
      <th>personal_id / FIN</th>
      <td><%= current_user.personal_id %></td>
    </tr>

    <tr>
      <th>Email address</th>
      <td><%= current_user.email %></td>
    </tr>

    <tr>
      <th>Contact number</th>
      <td><%= current_user.contact_no %></td>
    </tr>

  </thead>
</table><br>
<%= button_to "Update profile", edit_user_path(current_user.id), class: 'btn btn-lg btn-primary', method: :get %>
<br>

<%= button_to "Your Latest Admission", patient_admission_path(current_user.id), class: 'btn btn-lg btn-primary', method: :get %> <br>

<%= link_to 'See Past Admissions', patient_admissions_path, class:"btn btn-lg btn-primary" %>

</div>