config/routes.rb
Rails.application.routes.draw do

  get "login" => "sessions#new"
  post "login" => "sessions#create"
  delete "logout" => "sessions#destroy"
  resources :users
  resources :wards do
    patch 'reduce' => 'wards#reduce'
  end
  resources :patients do
    member do
      get :edit2
      get :edit3
      patch :update2
      patch :update3
    end
  end
  resources :patient_admissions
  root "sessions#new"
  resources :insurance
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/patient_admission.rb
class PatientAdmission < ApplicationRecord
  belongs_to :user
  has_one :ward

  # def to_s(digits)
  #   format("%.#{digits}f", self)
  # end

end

app/controllers/patient_admissions_controller.rb
class PatientAdmissionsController < ApplicationController
  before_action :is_authenticated
  around_filter :catch_not_found

  def index
    @patient = PatientAdmission.where(user_id: current_user.id)
    @ward = Ward.all
  end

  def new
    @patient_record = Patient.find_by(id: current_user.id)
    @income = @patient_record.income

    if @income < 3200
      @subsidy_C = 0.8
      @subsidy_B2 = 0.6
      @subsidy_B1 = 0.4
      @subsidy_A = 0
    elsif @income > 3200 && @income < 4000
      @subsidy_C = 0.6
      @subsidy_B2 = 0.4
      @subsidy_B1 = 0.2
      @subsidy_A = 0
    elsif @income > 4000 && @income < 6000
      @subsidy_C = 0.4
      @subsidy_B2 = 0.2
      @subsidy_B1 = 0
      @subsidy_A = 0
    end

    @patient = PatientAdmission.find_by(user_id: current_user.id)
    @ward = Ward.all
    @wardA = Ward.find_by(ward_type: 'A')
    @wardB1 = Ward.find_by(ward_type: 'B1')
    @wardB2 = Ward.find_by(ward_type: 'B2')
    @wardC = Ward.find_by(ward_type: 'C')
  end

  def show
    # else
    @patient = PatientAdmission.find_by! user_id: current_user.id, confirm: false
    # end
  end

  def edit
    @patient = PatientAdmission.find_by(user_id: params[:user_id])
    @patient_record = Patient.find_by(id: current_user.id)
    @income = @patient_record.income

    if @income < 3200
      @subsidy_C = 0.80
      @subsidy_B2 = 0.60
      @subsidy_B1 = 0.40
      @subsidy_A = 0.00
    elsif @income > 3200 && @income < 4000
      @subsidy_C = 0.60
      @subsidy_B2 = 0.40
      @subsidy_B1 = 0.20
      @subsidy_A = 0.00
    else @income > 4000 && @income < 6000
      @subsidy_C = 0.40
      @subsidy_B2 = 0.20
      @subsidy_B1 = 0.00
      @subsidy_A = 0.00
    end

    @patient = PatientAdmission.find_by(user_id: current_user.id)
    @ward = Ward.all
    @wardA = Ward.find_by(ward_type: 'A')
    @wardB1 = Ward.find_by(ward_type: 'B1')
    @wardB2 = Ward.find_by(ward_type: 'B2')
    @wardC = Ward.find_by(ward_type: 'C')
  end

  def update
    @patient = PatientAdmission.find_by(user_id: current_user.id)
    @patient_record = Patient.find_by(id: current_user.id)
    @income = @patient_record.income

    if @income < 3200
      @subsidy_C = 0.8
      @subsidy_B2 = 0.6
      @subsidy_B1 = 0.4
      @subsidy_A = 0
    elsif @income > 3200 && @income < 4000
      @subsidy_C = 0.6
      @subsidy_B2 = 0.4
      @subsidy_B1 = 0.2
      @subsidy_A = 0
    else @income > 4000 && @income < 6000
      @subsidy_C = 0.4
      @subsidy_B2 = 0.2
      @subsidy_B1 = 0
      @subsidy_A = 0
    end

    @ward = Ward.all
    @wardA = Ward.find_by(ward_type: 'A')
    @wardB1 = Ward.find_by(ward_type: 'B1')
    @wardB2 = Ward.find_by(ward_type: 'B2')
    @wardC = Ward.find_by(ward_type: 'C')


    if @patient.update!(patient_admission_params)
      @patient_record.minus_medisave(patient_admission_params[:claim_medisave])
      if (patient_admission_params[:ward_selected] == 'A')
        @wardA.change_availability
      elsif (patient_admission_params[:ward_selected] == 'B1')
        @wardB1.change_availability
      elsif (patient_admission_params[:ward_selected] == 'B2')
        @wardB2.change_availability
      elsif (patient_admission_params[:ward_selected] == 'C')
        @wardC.change_availability
      end
      redirect_to user_path(current_user.id)
    else
      render 'edit'
    end
  end

  private

  def patient_admission_params
    params.require(:patient).permit(:personal_id, :means_testing, :user_id, :ward_selected, :bill_amount, :claim_medisave, :pay_cash, :confirm)
  end

  def catch_not_found
    yield
  rescue ActiveRecord::RecordNotFound
    redirect_to user_path(current_user.id), :flash => { :notice => "You do not have pending admission." }
  end

end

app/helpers/patient_admissions_helper.rb
module PatientAdmissionsHelper
end

app/views/patient_admissions/_warda.html.erb
<%=form_for :patient, url: patient_admission_path(current_user.id), method: "Patch" do |f| %>
<fieldset>
  <legend> Bill Based On Ward A Chosen </legend>

  <p class="wardfont">
    <label>Subsidy available to you based on means testing</label><br>
    <%=@subsidy_A * 100 %>% <br>
    <label> Length of stay </label><br>
    <%=@patient.length_of_stay%><br>
    <label> Cost per day </label><br>
    $ <%=@wardA.cost_per_day%><br>
    <label> Before Subsidy </label><br>
    $ <%= f.text_field :bill_amount, value: @wardA.cost_per_day * @patient.length_of_stay %><br>
    <label> After Subsidy </label><br>
    $ <%= @aftersubsidy = @wardA.cost_per_day * @patient.length_of_stay %><br>
    <label> Medisave Claimable </label><br>
    <% if @patient_record.medisave > @aftersubsidy %>
    $ <%=f.text_field :claim_medisave, value:  @aftersubsidy %>
    <% elsif @patient_record.medisave < @aftersubsidy %>
    <%=f.text_field :claim_medisave, value:  @patient_record.medisave %>
    <% elsif @patient_record.medisave == 0 %>
    <%=f.text_field :claim_medisave, value: 0 %>
    <% end %> <br>
    <label> Cash payable </label><br>
    $ <% if @patient_record.medisave - @aftersubsidy > 0 %>
    <%= f.text_field :pay_cash, value: 0 %>
    <% elsif %>
    <% f.text_field :pay_cash, value: (@patient_record.medisave - @aftersubsidy).abs %>
    <% end %>
    <%= f.hidden_field :ward_selected, value: 'A' %>
    <%= f.hidden_field :user_id, value: current_user.id %>
    <%= f.hidden_field :confirm, value: true %> <br> <br>
    <%= f.submit "Save My Selection", class: "btn btn-primary btn-lg" %>
  </p>
</fieldset>
<%end%>

app/views/patient_admissions/_wardb1.html.erb
<%=form_for :patient, url: patient_admission_path(current_user.id), method: "Patch" do |f| %>
<fieldset>
  <legend> Bill Based On Ward B1 Chosen </legend>

  <p class="wardfont">
    <label>Subsidy available to you based on means testing</label><br>
    <%=@subsidy_B1 * 100 %>% <br>
    <label> Length of stay </label><br>
    <%=@patient.length_of_stay%><br>
    <label> Cost per day </label><br>
    $ <%=@wardB1.cost_per_day%><br>
    <label> Before Subsidy </label><br>
    $ <%= f.text_field :bill_amount, value: @wardB1.cost_per_day * @patient.length_of_stay %><br>
    <label> After Subsidy </label><br>
    $ <%= @aftersubsidy = @wardB1.cost_per_day * @patient.length_of_stay * (1 - @subsidy_B1) %><br>
    <label> Medisave Claimable </label><br>
    <% if @patient_record.medisave > @aftersubsidy %>
    $ <%=f.text_field :claim_medisave, value:  @aftersubsidy %>
    <% elsif @patient_record.medisave < @aftersubsidy %>
    <%=f.text_field :claim_medisave, value:  @patient_record.medisave %>
    <% elsif @patient_record.medisave == 0 %>
    <%=f.text_field :claim_medisave, value: 0 %>
    <% end %> <br>
    <label> Cash payable </label><br>
    $ <% if @patient_record.medisave - @aftersubsidy > 0 %>
    <%= f.text_field :pay_cash, value: 0 %>
    <% elsif %>
    <%= f.text_field :pay_cash, value: (@aftersubsidy - @patient_record.medisave).abs %>
    <% end %> <br>
    <%= f.hidden_field :ward_selected, value: 'B1' %>
    <%= f.hidden_field :user_id, value: current_user.id %>
    <%= f.hidden_field :confirm, value: true %> <br>
    <%= f.submit "Save My Selection", class: "btn btn-primary btn-lg" %>
  </p>
</fieldset>
<% end %>

app/views/patient_admissions/_wardb2.html.erb
<%=form_for :patient, url: patient_admission_path(current_user.id), method: "Patch" do |f| %>
<fieldset>
  <legend> Bill Based On Ward B2 Chosen </legend>

  <p class="wardfont">
    <label>Subsidy available to you based on means testing</label><br>
    <%=@subsidy_B2 * 100 %>% <br>
    <label> Length of stay </label><br>
    <%=@patient.length_of_stay%><br>
    <label> Cost per day </label><br>
    $ <%=@wardB2.cost_per_day%><br>
    <label> Before Subsidy </label><br>
    $ <%= f.text_field :bill_amount, value: @wardB2.cost_per_day * @patient.length_of_stay %><br>
    <label> After Subsidy </label><br>
    $ <%= @aftersubsidy = @wardB2.cost_per_day * @patient.length_of_stay * (1 - @subsidy_B2) %><br>
    <label> Medisave Claimable </label><br>
    <% if @patient_record.medisave > @aftersubsidy %>
    $ <%=f.text_field :claim_medisave, value:  @aftersubsidy %>
    <% elsif @patient_record.medisave < @aftersubsidy %>
    <%=f.text_field :claim_medisave, value:  @patient_record.medisave %>
    <% elsif @patient_record.medisave == 0 %>
    <%=f.text_field :claim_medisave, value: 0 %>
    <% end %> <br>
    <label> Cash payable </label><br>
    $ <% if @patient_record.medisave - @aftersubsidy > 0 %>
    <%= f.text_field :pay_cash, value: 0 %>
    <% elsif %>
    <% f.text_field :pay_cash, value: (@patient_record.medisave - @aftersubsidy).abs %>
    <% end %>
    <%= f.hidden_field :ward_selected, value: 'B2' %>
    <%= f.hidden_field :user_id, value: current_user.id %>
    <%= f.hidden_field :confirm, value: true %> <br> <br>
    <%= f.submit "Save My Selection", class: "btn btn-primary btn-lg" %>
  </p>
</fieldset>
<% end %>

app/views/patient_admissions/_wardc.html.erb
<%=form_for :patient, url: patient_admission_path(current_user.id), method: "Patch" do |f| %>
<fieldset>
  <legend> Bill Based On Ward C Chosen </legend>

  <p class="wardfont">
    <label>Subsidy available to you based on means testing</label><br>
    <%=@subsidy_C * 100 %>% <br>
    <label> Length of stay </label><br>
    <%=@patient.length_of_stay%><br>
    <label> Cost per day </label><br>
    $ <%=@wardC.cost_per_day%><br>
    <label> Before Subsidy </label><br>
    $ <%= f.text_field :bill_amount, value: @wardC.cost_per_day * @patient.length_of_stay %><br>
    <label> After Subsidy </label><br>
    $ <%= @aftersubsidy = @wardC.cost_per_day * @patient.length_of_stay * (1 - @subsidy_C)%><br>
    <label> Medisave Claimable </label><br>
    <% if @patient_record.medisave > @aftersubsidy %>
    $ <%=f.text_field :claim_medisave, value:  @aftersubsidy %>
    <% elsif @patient_record.medisave < @aftersubsidy %>
    <%=f.text_field :claim_medisave, value:  @patient_record.medisave %>
    <% elsif @patient_record.medisave == 0 %>
    <%=f.text_field :claim_medisave, value: 0 %>
    <% end %> <br>
    <label> Cash payable </label><br>
    $ <% if @patient_record.medisave - @aftersubsidy > 0 %>
    <%= f.text_field :pay_cash, value: 0 %>
    <% elsif %>
    <% f.text_field :pay_cash, value: (@patient_record.medisave - @aftersubsidy).abs %>
    <% end %>
    <%= f.hidden_field :ward_selected, value: 'C' %>
    <%= f.hidden_field :user_id, value: current_user.id %>
    <%= f.hidden_field :confirm, value: true %> <br> <br>
    <%= f.submit "Save My Selection", class: "btn btn-primary btn-lg" %>
  </p>
</fieldset>
<% end %>

app/views/patient_admissions/edit.html.erb
<div class="container">
  <div class="page header">
    <h1> Your Bill <small> <br> Click on the various ward selections to determine your estimated bill size.</small> </h1>
  </div>

  <div class="container selectbox">
    <% @ward.each do |w| %>
    <label class="radio-inline fontselect">
      <input type="radio" name="optradio" value="<%=w.ward_type%>"> Ward: <%= w.ward_type %> |
      <span> Availability: <%= w.availability %></span>
    </label>
    <%end%>
  </div>

  <div class="container">
    <br>
    <div id="ward">
    </div>
  </form>
</div>
</div>

<script>
$('input[type=radio][name=optradio]').change(function () {
  // check radio button value by this.value
  // hide div blocks by $('div#id').hide();
  if (this.value === 'A') {
    $('#ward').html('<%=j render :partial => "warda" %>')
  } else if (this.value === 'B1') {
    $('#ward').html('<%=j render :partial => "wardb1" %>')
  } else if (this.value === 'B2') {
    $('#ward').html('<%=j render :partial => "wardb2" %>')
  } else if (this.value === 'C') {
    $('#ward').html('<%=j render :partial => "wardc" %>')
  }
})
</script>

app/views/patient_admissions/index.html.erb
<div class="container">
  <div class="page-header">
    <h1> Your Index Page <br>
      <small> This lists all your admissions. </small></h1>
    </div>
  </div>

  <div class="container">
    <% @patient.each_with_index do |p, index| %>
    <table>
    <thead>
      <tr>
        <th> Admission number </th>
        <td><%= index + 1 %></td>
      </tr>
      <tr>
        <th> Treatment Description </th>
        <td><%= p.treatment%></td>
      </tr>
      <tr>
        <th> Start of Treatment </th>
        <td><%= p.start_treatment%></td>
      </tr>
      <tr>
        <th> End of Treatment </th>
        <td><%= p.end_treatment%></td>
      </tr>
      <tr>
        <th> Bill Amount </th>
        <td><%= p.bill_amount%></td>
      </tr>
      <tr>
        <th> Completed Admission </th>
        <td><%= p.confirm%></td>
      </tr>
    </table><br>
      <% end %>

      <%= link_to 'Personal Details Page', user_path(current_user.id), class:"btn btn-lg btn-primary" %>
    </div>

app/views/patient_admissions/show.html.erb
<div class="container page-header">
  <h1>Your Lastest Admission Summary</h1>
</div>

<div class="container">
  <h3>Your name is: <%= @current_user.name %> </h3>
  <br>
  <table class="responstable">
  <thead>
    <tr>
      <th>Treatment Description</th>
      <td><%= @patient.treatment %></td>
    </tr>
    <tr>
      <th>Length of Stay</th>
      <td><%= @patient.length_of_stay %></td>

    </tr>
    <tr>
      <th>Ward Selected</th>
      <td><%= @patient.ward_selected %></td>

    </tr>
    <tr>
      <th>Bill Amount</th>
      <td><%= @patient.bill_amount %></td>

    </tr>
    <tr>
      <th>Treatment Start Date</th>
      <td><%= @patient.start_treatment %></td>

    </tr>
    <tr>
      <th>Treatment End Date</th>
      <td><%= @patient.end_treatment %></td>

    </tr>
    <tr>
      <th>Doctor-in-charge</th>
      <td><%= @patient.doctor_in_charge %></td>

    </tr>
    <tr>
      <th>Opted for Financial Counselor</th>
      <td><%= @patient.financial_counsel %></td>

    </tr>
    <tr>
      <th>Admission Completed</th>
      <td><%= @patient.confirm %></td>
    </tr>
  </thead>
  </table>
  <br>
    <%= button_to "Next", edit_patient_path, class: 'btn btn-lg btn-primary', method: :get %>

  </div>