config/routes.rb
Rails.application.routes.draw do

  get "login" => "sessions#new"
  post "login" => "sessions#create"
  delete "logout" => "sessions#destroy"
  resources :users
  resources :wards do
    patch 'reduce' => 'wards#reduce'
  end
  resources :patients do
    member do
      get :edit2
      get :edit3
      patch :update2
      patch :update3
    end
  end
  resources :patient_admissions
  root "sessions#new"
  resources :insurance
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Efc</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'patient_admissions', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <nav class="navbar navbar-inverse">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand">eFC</a>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <% if current_user.blank? %>
          <li><%= link_to 'Sign Up', new_user_path %></li>
          <li><%= link_to 'Login', root_path %></li>
          <% end %>
          <% if current_user.present? %>
          <li><%= link_to 'Logout', logout_path, method: "delete" %></li>
          <% end %>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <% if current_user.present? %>
          <li><a>Logged in as: </a></li>
          <li><%= link_to current_user.name, user_path(current_user.id) %></li>
          <% end %>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>
  <%= yield %>
  <footer class="body">
    <div class="container">
      <p class="muted credit"> Bringing you seamless patient admission process.
      </p>
    </div>
  </footer>
</body>
</html>